### ISSUE TITLE
BIM 360 Docs

### ISSUE THREAD

**Issue by JuanTenaF** [Autodesk-Forge/bim360appstore-model.derivative-nodejs-xls.exporter#14]
BIM360 Team projects are available when using the tool, but not for BIM360 Docs projects.

**Comment by jaimerosales** [comment]
Yes, BIM 360 Docs projects are not available unless you go through the configuration process. 
You can either add this as an integration to your BIM 360 Account from the available apps, or you can check in the top right corner the config section which will give you the client_id to include in your custom integrations. Also there is a section that will show you those steps in there. See attached. 

<img width="1882" alt="screen shot 2018-08-08 at 12 08 32 pm" src="https://user-images.githubusercontent.com/8932722/43849654-eef0b82a-9b03-11e8-87c7-b53d6d94e6ef.png">
