### ISSUE TITLE
x-ads-force 

### ISSUE THREAD

**Issue by augustogoncalves** [Autodesk-Forge/bim360appstore-model.derivative-nodejs-xls.exporter#25]
for GET Properties endpoint, [this function](https://github.com/Autodesk-Forge/bim360appstore-model.derivative-nodejs-xls.exporter/blob/master/www/js/ForgeXLS.js#L35) needs to pass the x-ads-force:true header.

**Comment by libvarun** [comment]
this one is solved with last PR, it's added as query string [here](https://github.com/Autodesk-Forge/bim360appstore-model.derivative-nodejs-xls.exporter/blob/master/www/js/ForgeXLS.js#L62)
