### ISSUE TITLE
Copy to clipboard button not working

### ISSUE THREAD

**Issue by augustogoncalves** [Autodesk-Forge/bim360appstore-model.derivative-nodejs-xls.exporter#5]
#Probably missing on index.html

```
<script>
  new Clipboard('.input-group-addon');
</script>
```

[See here](https://github.com/Autodesk-Forge/bim360appstore-data.management-nodejs-transfer.storage/blob/master/www/index.html#L159).

**Comment by wallabyway** [comment]
added clipboard.js like other examples
